# Example configuration file for Python Template
# Copy this file to config.toml and customize as needed

[app]
name = "python-template"
version = "0.1.0"
debug = false
environment = "development"

[logging]
level = "INFO"
format = "standard"  # "standard" or "json"
file = ""  # Set to a file path to enable file logging
rotation = "10 MB"
retention = "1 week"
json_format = false

[performance]
timeout = 30
max_retries = 3
buffer_size = 1024
concurrent_workers = 4

[security]
# Set these via environment variables in production
secret_key = ""
api_key = ""
ssl_verify = true
allowed_hosts = ["localhost", "127.0.0.1"]
