"""Utilities package.

Provides a collection of utility functions and classes for the project.
Includes file, JSON, date, and other common helpers.
"""

from .common_utils import (
    Settings,
    async_batch_process,
    async_batch_process_concurrent,
    async_retry_on_exception,
    batch_process,
    chunk_list,
    clamp,
    deep_merge_dict,
    ensure_list,
    filter_dict,
    first_non_none,
    flatten_dict,
    generate_uuid,
    get_settings,
    merge_dicts,
    reload_settings,
    remove_empty_values,
    remove_none_values,
    retry_on_exception,
    safe_get,
    safe_set,
    unflatten_dict,
    validate_email,
)
from .context import (
    Context,
    ContextManager,
    async_context_scope,
    clear_global,
    context_scope,
    get_context,
    get_global,
    get_global_context,
    run_in_context,
    set_global,
)
from .date_utils import (
    add_days,
    add_hours,
    add_minutes,
    format_datetime,
    from_unix_timestamp,
    get_current_date,
    get_current_time,
    get_month_start,
    get_time_difference,
    get_timestamp,
    get_unix_timestamp,
    get_week_start,
    humanize_timedelta,
    is_weekend,
    parse_datetime,
    parse_timestamp,
)
from .decorator_utils import (
    AsyncContextTimer,
    ContextTimer,
    async_catch_exceptions,
    async_log_calls,
    async_retry_decorator,
    async_timing_decorator,
    catch_exceptions,
    deprecated,
    log_calls,
    retry,
    retry_decorator,
    singleton,
    timing,
    timing_decorator,
)
from .file_utils import (
    async_calculate_file_hash,
    async_copy_file,
    async_delete_file,
    async_list_files,
    async_move_file,
    async_read_text_file,
    async_write_text_file,
    calculate_file_hash,
    copy_file,
    delete_file,
    ensure_directory,
    format_file_size,
    get_file_size,
    list_files,
    move_file,
    read_text_file,
    sanitize_filename,
    write_text_file,
)
from .json_utils import (
    async_load_json_batch,
    async_merge_json_files,
    async_read_json,
    async_write_json,
    json_path_get,
    merge_json_files,
    pretty_print_json,
    read_json,
    safe_json_dumps,
    safe_json_loads,
    validate_json_schema,
    write_json,
)
from .logger_util import get_logger

__all__ = [
    # Logger
    "get_logger",
    # Common
    "chunk_list",
    "flatten_dict",
    "unflatten_dict",
    "merge_dicts",
    "filter_dict",
    "deep_merge_dict",
    "safe_get",
    "safe_set",
    "remove_none_values",
    "remove_empty_values",
    "batch_process",
    "async_batch_process",
    "async_batch_process_concurrent",
    "retry_on_exception",
    "async_retry_on_exception",
    "generate_uuid",
    "clamp",
    "ensure_list",
    "first_non_none",
    "validate_email",
    "Settings",
    "get_settings",
    "reload_settings",
    # Context
    "Context",
    "ContextManager",
    "get_context",
    "get_global_context",
    "context_scope",
    "async_context_scope",
    "run_in_context",
    "set_global",
    "get_global",
    "clear_global",
    # Date
    "get_timestamp",
    "parse_timestamp",
    "format_datetime",
    "parse_datetime",
    "get_current_date",
    "get_current_time",
    "get_unix_timestamp",
    "from_unix_timestamp",
    "get_time_difference",
    "is_weekend",
    "humanize_timedelta",
    "add_days",
    "add_hours",
    "add_minutes",
    "get_week_start",
    "get_month_start",
    # Decorators
    "timing",
    "retry",
    "catch_exceptions",
    "log_calls",
    "deprecated",
    "singleton",
    "ContextTimer",
    "AsyncContextTimer",
    "timing_decorator",
    "retry_decorator",
    "async_timing_decorator",
    "async_retry_decorator",
    "async_catch_exceptions",
    "async_log_calls",
    # File
    "ensure_directory",
    "get_file_size",
    "format_file_size",
    "calculate_file_hash",
    "copy_file",
    "move_file",
    "delete_file",
    "list_files",
    "read_text_file",
    "write_text_file",
    "sanitize_filename",
    "async_read_text_file",
    "async_write_text_file",
    "async_copy_file",
    "async_move_file",
    "async_delete_file",
    "async_calculate_file_hash",
    "async_list_files",
    # JSON
    "read_json",
    "write_json",
    "safe_json_loads",
    "safe_json_dumps",
    "merge_json_files",
    "pretty_print_json",
    "validate_json_schema",
    "json_path_get",
    "async_read_json",
    "async_write_json",
    "async_merge_json_files",
    "async_load_json_batch",
    "get_time_difference",
]
