#!/usr/bin/env python3
"""Validate ai_docs structure, links, layering, and thin adapters."""

from __future__ import annotations

import argparse
import importlib.util
import re
from pathlib import Path

LINK_PATTERN = re.compile(r"\[[^\]]+\]\(([^)]+)\)")
GENERATED_MARKER = "Generated by scripts/sync_ai_adapters.py"
VERIFICATION_COMMANDS = [
    "uv run ruff check src tests scripts",
    "uv run ruff format --check src tests scripts",
    "uv run mypy src",
    "uv run pytest",
    "pnpm --prefix frontend lint",
    "pnpm --prefix frontend typecheck",
    "pnpm --prefix frontend test",
    "pnpm --prefix frontend build",
]
FORBIDDEN_LEGACY_PATHS = [
    "ai_docs/AI_TOOLING_STANDARDS.md",
    "ai_docs/BACKEND_STANDARDS.md",
    "ai_docs/FRONTEND_STANDARDS.md",
    "ai_docs/SCRIPTS_GUIDE.md",
    "ai_docs/MODELS_GUIDE.md",
    "ai_docs/SETTINGS_GUIDE.md",
    "ai_docs/SDK_USAGE.md",
    "ai_docs/PRE_COMMIT_GUIDE.md",
    "ai_docs/frontend_design/DESIGN_SYSTEM.md",
]
REQUIRED_DOCS = [
    "ai_adapter_config.json",
    "ai_docs/START_HERE.md",
    "ai_docs/INDEX.md",
    "ai_docs/current/architecture.md",
    "ai_docs/current/backend.md",
    "ai_docs/current/frontend.md",
    "ai_docs/current/scripts.md",
    "ai_docs/current/release.md",
    "ai_docs/standards/engineering.md",
    "ai_docs/standards/backend.md",
    "ai_docs/standards/frontend.md",
    "ai_docs/standards/design-system.md",
    "ai_docs/standards/documentation.md",
    "ai_docs/workflows/start-task.md",
    "ai_docs/workflows/add-backend-feature.md",
    "ai_docs/workflows/add-frontend-feature.md",
    "ai_docs/workflows/add-fullstack-feature.md",
    "ai_docs/workflows/fix-bug.md",
    "ai_docs/workflows/review-change.md",
    "ai_docs/workflows/release.md",
    "ai_docs/reference/verification.md",
    "ai_docs/reference/project-structure.md",
    "ai_docs/reference/naming-and-paths.md",
    "ai_docs/reference/tool-entrypoints.md",
    "ai_docs/decisions/adr-001-ai-docs-source-of-truth.md",
    "ai_docs/decisions/adr-002-tool-adapter-strategy.md",
]


def get_repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def load_sync_module():
    script_path = Path(__file__).with_name("sync_ai_adapters.py")
    spec = importlib.util.spec_from_file_location("sync_ai_adapters", script_path)
    if spec is None or spec.loader is None:
        raise RuntimeError("Unable to load sync_ai_adapters.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def get_adapter_files(root: Path) -> list[str]:
    sync_module = load_sync_module()
    return [
        path.relative_to(root).as_posix()
        for path in sync_module.list_expected_adapter_files(root)
    ]


def classify_doc(path: Path, root: Path) -> str:
    relative = path.relative_to(root).as_posix()
    if relative == "ai_docs/START_HERE.md":
        return "start_here"
    if relative == "ai_docs/INDEX.md":
        return "index"
    if relative.startswith("ai_docs/current/"):
        return "current"
    if relative.startswith("ai_docs/standards/"):
        return "standards"
    if relative.startswith("ai_docs/workflows/"):
        return "workflows"
    if relative.startswith("ai_docs/reference/"):
        return "reference"
    if relative.startswith("ai_docs/decisions/"):
        return "decisions"
    return "legacy"


def allowed_targets(category: str) -> set[str]:
    mapping = {
        "start_here": {"index", "reference", "current"},
        "index": {
            "start_here",
            "index",
            "current",
            "standards",
            "workflows",
            "reference",
            "decisions",
            "legacy",
        },
        "current": {"reference"},
        "standards": {"reference", "current"},
        "workflows": {"current", "standards", "reference"},
        "reference": set(),
        "decisions": {
            "start_here",
            "index",
            "current",
            "standards",
            "workflows",
            "reference",
            "decisions",
            "legacy",
        },
        "legacy": {"start_here", "index", "current", "standards", "reference"},
    }
    return mapping[category]


def iter_ai_markdown(root: Path) -> list[Path]:
    return sorted((root / "ai_docs").rglob("*.md"))


def extract_links(path: Path) -> list[str]:
    content = path.read_text(encoding="utf-8")
    return LINK_PATTERN.findall(content)


def resolve_link(path: Path, link: str) -> Path | None:
    if link.startswith(("http://", "https://", "mailto:")):
        return None
    if link.startswith("#"):
        return None
    clean_link = link.split("#", 1)[0]
    if not clean_link:
        return None
    return (path.parent / clean_link).resolve()


def check_required_files(root: Path) -> list[str]:
    issues: list[str] = []
    for relative_path in REQUIRED_DOCS + get_adapter_files(root):
        path = root / relative_path
        if not path.exists():
            issues.append(f"Missing required file: {relative_path}")
    return issues


def check_links(root: Path) -> tuple[list[str], dict[Path, list[Path]]]:
    issues: list[str] = []
    graph: dict[Path, list[Path]] = {}
    for path in iter_ai_markdown(root):
        graph[path] = []
        source_category = classify_doc(path, root)
        for link in extract_links(path):
            target = resolve_link(path, link)
            if target is None:
                continue
            if not target.exists():
                issues.append(f"Broken link in {path.relative_to(root)}: {link}")
                continue
            if root / "ai_docs" in target.parents or target == root / "ai_docs":
                target_category = classify_doc(target, root)
                if target_category not in allowed_targets(source_category):
                    issues.append(
                        "Invalid ai_docs reference direction: "
                        f"{path.relative_to(root)} -> {target.relative_to(root)}"
                    )
                graph[path].append(target)
    return issues, graph


def detect_cycles(graph: dict[Path, list[Path]]) -> list[str]:
    issues: list[str] = []
    visiting: set[Path] = set()
    visited: set[Path] = set()

    def visit(node: Path, stack: list[Path]) -> None:
        if node in visited:
            return
        if node in visiting:
            cycle = " -> ".join(path.name for path in stack + [node])
            issues.append(f"Cycle detected in ai_docs references: {cycle}")
            return
        visiting.add(node)
        for target in graph.get(node, []):
            visit(target, stack + [node])
        visiting.remove(node)
        visited.add(node)

    for node in graph:
        visit(node, [])
    return issues


def check_legacy_docs(root: Path) -> list[str]:
    issues: list[str] = []
    for relative_path in FORBIDDEN_LEGACY_PATHS:
        if (root / relative_path).exists():
            issues.append(f"Legacy file should be removed: {relative_path}")
    return issues


def check_unique_verification_commands(root: Path) -> list[str]:
    issues: list[str] = []
    adapter_files = get_adapter_files(root)
    allowed_path = root / "ai_docs" / "reference" / "verification.md"
    for path in iter_ai_markdown(root):
        if path == allowed_path:
            continue
        content = path.read_text(encoding="utf-8")
        for command in VERIFICATION_COMMANDS:
            if command in content:
                issues.append(
                    f"Verification command duplicated outside reference/verification.md: "
                    f"{path.relative_to(root)}"
                )
                break
    for relative_path in adapter_files:
        content = (root / relative_path).read_text(encoding="utf-8")
        for command in VERIFICATION_COMMANDS:
            if command in content:
                issues.append(
                    f"Verification command duplicated in adapter: {relative_path}"
                )
                break
    return issues


def check_adapters(root: Path) -> list[str]:
    issues: list[str] = []
    sync_module = load_sync_module()
    adapter_files = get_adapter_files(root)
    for relative_path in adapter_files:
        content = (root / relative_path).read_text(encoding="utf-8")
        if GENERATED_MARKER not in content:
            issues.append(f"Adapter missing generated marker: {relative_path}")
        if "ai_docs/START_HERE.md" not in content and "AGENTS.md" not in content:
            issues.append(f"Adapter missing start routing reference: {relative_path}")
        if "verification.md" not in content:
            issues.append(f"Adapter missing verification reference: {relative_path}")
    stale_files = sync_module.find_stale_generated_files(root)
    for path in stale_files:
        issues.append(
            f"Stale generated adapter should be removed or pruned: "
            f"{path.relative_to(root).as_posix()}"
        )
    return issues


def collect_issues(root: Path) -> list[str]:
    issues = []
    issues.extend(check_required_files(root))
    link_issues, graph = check_links(root)
    issues.extend(link_issues)
    issues.extend(detect_cycles(graph))
    issues.extend(check_legacy_docs(root))
    issues.extend(check_unique_verification_commands(root))
    issues.extend(check_adapters(root))
    return issues


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=get_repo_root(),
        help="Repository root. Defaults to the current project root.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    issues = collect_issues(args.root.resolve())
    if not issues:
        print("AI docs structure is valid.")
        return 0

    print("AI docs validation failed:")
    for issue in issues:
        print(f"- {issue}")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
