#!/usr/bin/env python3
"""Generate thin AI adapter files from canonical ai_docs references."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
from textwrap import dedent

GENERATED_MARKER = "<!-- Generated by scripts/sync_ai_adapters.py -->"


def get_repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def rel_link(file_path: Path, target: str) -> str:
    return os.path.relpath(target, start=file_path.parent).replace(os.sep, "/")


def markdown_link(file_path: Path, target: str, label: str) -> str:
    return f"[{label}]({rel_link(file_path, target)})"


def build_agents_md(root: Path) -> str:
    path = root / "AGENTS.md"
    start_here = markdown_link(path, "ai_docs/START_HERE.md", "ai_docs/START_HERE.md")
    index = markdown_link(path, "ai_docs/INDEX.md", "ai_docs/INDEX.md")
    verification = markdown_link(
        path, "ai_docs/reference/verification.md", "ai_docs/reference/verification.md"
    )
    return dedent(
        f"""\
        # Project Agent Entrypoint

        {GENERATED_MARKER}

        This file is the cross-tool entrypoint for this repository.

        ## Read order

        1. Start at {start_here}
        2. Use {index} to choose the right task path
        3. Use {verification} before claiming completion

        ## Working rules

        - Treat `ai_docs/` as the only detailed source of truth
        - Read `current/` before `standards/` and `workflows/`
        - Keep changes minimal, typed, and explicit
        - Update docs whenever behavior, structure, scripts, adapters, or public APIs change
        """
    )


def build_claude_md(root: Path) -> str:
    path = root / "CLAUDE.md"
    agents = markdown_link(path, "AGENTS.md", "AGENTS.md")
    tool_entrypoints = markdown_link(
        path,
        "ai_docs/reference/tool-entrypoints.md",
        "ai_docs/reference/tool-entrypoints.md",
    )
    verification = markdown_link(
        path, "ai_docs/reference/verification.md", "ai_docs/reference/verification.md"
    )
    start_task = markdown_link(
        path, "ai_docs/workflows/start-task.md", "ai_docs/workflows/start-task.md"
    )
    backend = markdown_link(
        path,
        ".claude/skills/backend-engineering-playbook/SKILL.md",
        ".claude/skills/backend-engineering-playbook/SKILL.md",
    )
    project = markdown_link(
        path,
        ".claude/skills/project-development-playbook/SKILL.md",
        ".claude/skills/project-development-playbook/SKILL.md",
    )
    return dedent(
        f"""\
        # Claude Code Project Instructions

        {GENERATED_MARKER}

        ## Read order

        1. Start at {agents}
        2. Check tool entrypoints in {tool_entrypoints}
        3. Use {start_task} to route the task
        4. Run the relevant section in {verification}

        ## Claude-specific notes

        - Use {project} for general project work
        - Use {backend} for backend-heavy tasks
        - Keep this file thin; detailed rules live in `ai_docs/`
        """
    )


def build_rule_file(
    root: Path, relative_path: str, description: str, globs: str, bullets: list[str]
) -> str:
    lines = [
        "---",
        f"description: {description}",
        f"globs: {globs}",
        "---",
        GENERATED_MARKER,
    ]
    lines.extend(f"- {bullet}" for bullet in bullets)
    return "\n".join(lines) + "\n"


def build_agents_rule(root: Path, relative_path: str, bullets: list[str]) -> str:
    return (
        dedent(
            f"""\
        ---
        trigger: always_on
        ---

        {GENERATED_MARKER}
        """
        )
        + "".join(f"\n- {bullet}" for bullet in bullets)
        + "\n"
    )


def build_skill(
    root: Path,
    relative_path: str,
    name: str,
    description: str,
    title: str,
    bullets: list[str],
) -> str:
    lines = [
        "---",
        f"name: {name}",
        f"description: {description}",
        "---",
        GENERATED_MARKER,
        f"# {title}",
        "",
    ]
    lines.extend(f"- {bullet}" for bullet in bullets)
    return "\n".join(lines) + "\n"


def build_cursor_bullets(root: Path, relative_path: str, *, domain: str) -> list[str]:
    path = root / relative_path
    start_here = markdown_link(path, "ai_docs/START_HERE.md", "ai_docs/START_HERE.md")
    index = markdown_link(path, "ai_docs/INDEX.md", "ai_docs/INDEX.md")
    verification = markdown_link(
        path, "ai_docs/reference/verification.md", "ai_docs/reference/verification.md"
    )
    mapping = {
        "project": [
            f"Start at {start_here}",
            f"Use {index} to choose the matching task workflow",
            "Treat `ai_docs/` as the only detailed source of truth",
            f"Run the relevant section in {verification} before completion",
        ],
        "backend": [
            f"Read {markdown_link(path, 'ai_docs/current/backend.md', 'ai_docs/current/backend.md')}",
            f"Follow {markdown_link(path, 'ai_docs/standards/backend.md', 'ai_docs/standards/backend.md')}",
            f"Route implementation via {markdown_link(path, 'ai_docs/workflows/add-backend-feature.md', 'ai_docs/workflows/add-backend-feature.md')}",
            f"Run the backend section in {verification}",
        ],
        "frontend": [
            f"Read {markdown_link(path, 'ai_docs/current/frontend.md', 'ai_docs/current/frontend.md')}",
            f"Follow {markdown_link(path, 'ai_docs/standards/frontend.md', 'ai_docs/standards/frontend.md')} and {markdown_link(path, 'ai_docs/standards/design-system.md', 'ai_docs/standards/design-system.md')}",
            f"Route implementation via {markdown_link(path, 'ai_docs/workflows/add-frontend-feature.md', 'ai_docs/workflows/add-frontend-feature.md')}",
            f"Run the frontend section in {verification}",
        ],
        "config": [
            f"Read {markdown_link(path, 'ai_docs/current/backend.md', 'ai_docs/current/backend.md')} for current settings behavior",
            f"Use {markdown_link(path, 'ai_docs/standards/backend.md', 'ai_docs/standards/backend.md')} for configuration and safety rules",
            f"Use {markdown_link(path, 'ai_docs/reference/naming-and-paths.md', 'ai_docs/reference/naming-and-paths.md')} for import and path rules",
            f"Run the backend section in {verification}",
        ],
        "error": [
            f"Read {markdown_link(path, 'ai_docs/standards/engineering.md', 'ai_docs/standards/engineering.md')}",
            f"Follow {markdown_link(path, 'ai_docs/standards/backend.md', 'ai_docs/standards/backend.md')} for explicit error handling",
            f"Use {markdown_link(path, 'ai_docs/workflows/fix-bug.md', 'ai_docs/workflows/fix-bug.md')} for bugfix flow",
            f"Run the relevant section in {verification}",
        ],
        "code_style": [
            f"Start at {start_here}",
            f"Use {markdown_link(path, 'ai_docs/standards/engineering.md', 'ai_docs/standards/engineering.md')} for shared coding rules",
            f"Use {markdown_link(path, 'ai_docs/reference/naming-and-paths.md', 'ai_docs/reference/naming-and-paths.md')} for naming and import rules",
            f"Run the relevant section in {verification}",
        ],
        "logging": [
            f"Read {markdown_link(path, 'ai_docs/current/backend.md', 'ai_docs/current/backend.md')} for current logging entrypoints",
            f"Follow {markdown_link(path, 'ai_docs/standards/backend.md', 'ai_docs/standards/backend.md')} for safety and logging rules",
            f"Use {markdown_link(path, 'ai_docs/workflows/add-backend-feature.md', 'ai_docs/workflows/add-backend-feature.md')} for implementation flow",
            f"Run the backend section in {verification}",
        ],
        "models": [
            f"Read {markdown_link(path, 'ai_docs/current/backend.md', 'ai_docs/current/backend.md')} for current model exports",
            f"Follow {markdown_link(path, 'ai_docs/standards/backend.md', 'ai_docs/standards/backend.md')} for model conventions",
            f"Use {markdown_link(path, 'ai_docs/reference/naming-and-paths.md', 'ai_docs/reference/naming-and-paths.md')} for import rules",
            f"Run the backend section in {verification}",
        ],
        "testing": [
            f"Read {markdown_link(path, 'ai_docs/standards/engineering.md', 'ai_docs/standards/engineering.md')}",
            f"Use {markdown_link(path, 'ai_docs/workflows/review-change.md', 'ai_docs/workflows/review-change.md')} for review and regression expectations",
            f"Use {markdown_link(path, 'ai_docs/reference/verification.md', 'ai_docs/reference/verification.md')} as the only command source",
            "Add or update tests for behavior changes and bugfixes",
        ],
        "tooling": [
            f"Read {markdown_link(path, 'ai_docs/current/scripts.md', 'ai_docs/current/scripts.md')}",
            f"Use {markdown_link(path, 'ai_docs/standards/engineering.md', 'ai_docs/standards/engineering.md')} for shared workflow rules",
            f"Use {markdown_link(path, 'ai_docs/reference/verification.md', 'ai_docs/reference/verification.md')} as the only command source",
            f"Check entrypoint policy in {markdown_link(path, 'ai_docs/reference/tool-entrypoints.md', 'ai_docs/reference/tool-entrypoints.md')}",
        ],
        "structure": [
            f"Read {markdown_link(path, 'ai_docs/current/architecture.md', 'ai_docs/current/architecture.md')}",
            f"Use {markdown_link(path, 'ai_docs/reference/project-structure.md', 'ai_docs/reference/project-structure.md')} as the only structure reference",
            f"Use {markdown_link(path, 'ai_docs/reference/naming-and-paths.md', 'ai_docs/reference/naming-and-paths.md')} for naming rules",
            f"Run the relevant section in {verification}",
        ],
    }
    bullets = mapping[domain]
    if not any("START_HERE" in bullet for bullet in bullets):
        bullets = [f"Start at {start_here}", *bullets]
    return bullets


def build_adapter_map(root: Path) -> dict[Path, str]:
    adapters: dict[Path, str] = {
        root / "AGENTS.md": build_agents_md(root),
        root / "CLAUDE.md": build_claude_md(root),
    }

    adapters[root / ".agents" / "rules" / "project-development.md"] = build_agents_rule(
        root,
        ".agents/rules/project-development.md",
        bullets=[
            f"Start at {markdown_link(root / '.agents/rules/project-development.md', 'ai_docs/START_HERE.md', 'ai_docs/START_HERE.md')}",
            f"Use {markdown_link(root / '.agents/rules/project-development.md', 'ai_docs/INDEX.md', 'ai_docs/INDEX.md')} to route the task",
            f"Use {markdown_link(root / '.agents/rules/project-development.md', 'ai_docs/standards/engineering.md', 'ai_docs/standards/engineering.md')} for shared workflow rules",
            f"Use {markdown_link(root / '.agents/rules/project-development.md', 'ai_docs/reference/verification.md', 'ai_docs/reference/verification.md')} before completion",
        ],
    )
    adapters[root / ".agents" / "rules" / "code-style.md"] = build_agents_rule(
        root,
        ".agents/rules/code-style.md",
        bullets=[
            f"Start at {markdown_link(root / '.agents/rules/code-style.md', 'ai_docs/START_HERE.md', 'ai_docs/START_HERE.md')}",
            f"Use {markdown_link(root / '.agents/rules/code-style.md', 'ai_docs/standards/engineering.md', 'ai_docs/standards/engineering.md')} for shared coding expectations",
            f"Use {markdown_link(root / '.agents/rules/code-style.md', 'ai_docs/standards/backend.md', 'ai_docs/standards/backend.md')} for backend-specific style",
            f"Use {markdown_link(root / '.agents/rules/code-style.md', 'ai_docs/reference/naming-and-paths.md', 'ai_docs/reference/naming-and-paths.md')} for naming and import rules",
            f"Use {markdown_link(root / '.agents/rules/code-style.md', 'ai_docs/reference/verification.md', 'ai_docs/reference/verification.md')} before completion",
        ],
    )
    adapters[
        root / ".agents" / "skills" / "backend-engineering-playbook" / "SKILL.md"
    ] = build_skill(
        root,
        ".agents/skills/backend-engineering-playbook/SKILL.md",
        name="backend-engineering-playbook",
        description="Use when implementing backend API or service tasks that need architecture boundaries, data safety, and verification.",
        title="Backend Engineering Playbook",
        bullets=[
            f"Start at {markdown_link(root / '.agents/skills/backend-engineering-playbook/SKILL.md', 'ai_docs/START_HERE.md', 'ai_docs/START_HERE.md')}",
            f"Read {markdown_link(root / '.agents/skills/backend-engineering-playbook/SKILL.md', 'ai_docs/current/backend.md', 'ai_docs/current/backend.md')} for the current backend shape",
            f"Follow {markdown_link(root / '.agents/skills/backend-engineering-playbook/SKILL.md', 'ai_docs/standards/backend.md', 'ai_docs/standards/backend.md')} for backend rules",
            f"Route implementation via {markdown_link(root / '.agents/skills/backend-engineering-playbook/SKILL.md', 'ai_docs/workflows/add-backend-feature.md', 'ai_docs/workflows/add-backend-feature.md')}",
            f"Run the backend section in {markdown_link(root / '.agents/skills/backend-engineering-playbook/SKILL.md', 'ai_docs/reference/verification.md', 'ai_docs/reference/verification.md')}",
        ],
    )
    adapters[
        root / ".agents" / "skills" / "project-development-playbook" / "SKILL.md"
    ] = build_skill(
        root,
        ".agents/skills/project-development-playbook/SKILL.md",
        name="project-development-playbook",
        description="Use when implementing project tasks that need consistent coding standards, verification, and frontend stack defaults.",
        title="Project Development Playbook",
        bullets=[
            f"Start at {markdown_link(root / '.agents/skills/project-development-playbook/SKILL.md', 'ai_docs/START_HERE.md', 'ai_docs/START_HERE.md')}",
            f"Use {markdown_link(root / '.agents/skills/project-development-playbook/SKILL.md', 'ai_docs/INDEX.md', 'ai_docs/INDEX.md')} to choose backend, frontend, or full-stack flow",
            f"Follow {markdown_link(root / '.agents/skills/project-development-playbook/SKILL.md', 'ai_docs/workflows/start-task.md', 'ai_docs/workflows/start-task.md')} before implementation",
            f"Use {markdown_link(root / '.agents/skills/project-development-playbook/SKILL.md', 'ai_docs/standards/engineering.md', 'ai_docs/standards/engineering.md')} for shared rules",
            f"Run the matching section in {markdown_link(root / '.agents/skills/project-development-playbook/SKILL.md', 'ai_docs/reference/verification.md', 'ai_docs/reference/verification.md')}",
        ],
    )

    cursor_specs = {
        ".cursor/rules/project-development-standards.mdc": (
            "Project-wide entrypoint for repository docs and workflows.",
            "**/*",
            "project",
        ),
        ".cursor/rules/backend-python-service-standards.mdc": (
            "Thin backend adapter for current backend state and workflow references.",
            "**/*.py",
            "backend",
        ),
        ".cursor/rules/frontend-react-typescript-vite-tailwind.mdc": (
            "Thin frontend adapter for current starter state and UI workflow references.",
            "frontend/**/*",
            "frontend",
        ),
        ".cursor/rules/python-configuration-management.mdc": (
            "Thin adapter for settings, configuration, and path rules.",
            "**/setting.py, **/config.py, **/.env*",
            "config",
        ),
        ".cursor/rules/python-decorator-patterns.mdc": (
            "Thin adapter for backend utility and implementation rules.",
            "**/decorator_utils.py, **/decorators.py",
            "backend",
        ),
        ".cursor/rules/python-error-handling.mdc": (
            "Thin adapter for explicit error-handling and bugfix workflow references.",
            "**/*.py",
            "error",
        ),
        ".cursor/rules/python-general-coding-style.mdc": (
            "Thin adapter for shared Python coding and naming rules.",
            "**/*.py",
            "code_style",
        ),
        ".cursor/rules/python-logging-practices.mdc": (
            "Thin adapter for current logging entrypoints and backend logging rules.",
            "**/logger_util.py, **/logging*.py",
            "logging",
        ),
        ".cursor/rules/python-performance-optimization.mdc": (
            "Thin adapter for backend implementation flow and verification references.",
            "**/utils/**/*.py",
            "backend",
        ),
        ".cursor/rules/python-pydantic-models.mdc": (
            "Thin adapter for model exports, conventions, and import rules.",
            "**/models/**/*.py",
            "models",
        ),
        ".cursor/rules/python-testing-practices.mdc": (
            "Thin adapter for testing expectations and verification entrypoints.",
            "**/tests/**/*.py, **/test_*.py",
            "testing",
        ),
        ".cursor/rules/python-tooling-standards.mdc": (
            "Thin adapter for scripts, tooling, and verification references.",
            "**/pyproject.toml, **/.pre-commit-config.yaml",
            "tooling",
        ),
        ".cursor/rules/python-utility-structure.mdc": (
            "Thin adapter for project structure and naming references.",
            "**/utils/**/*.py",
            "structure",
        ),
    }
    for relative_path, (description, globs, domain) in cursor_specs.items():
        adapters[root / relative_path] = build_rule_file(
            root,
            relative_path,
            description=description,
            globs=globs,
            bullets=build_cursor_bullets(root, relative_path, domain=domain),
        )
    adapters[
        root / ".cursor" / "skills" / "backend-engineering-playbook" / "SKILL.md"
    ] = build_skill(
        root,
        ".cursor/skills/backend-engineering-playbook/SKILL.md",
        name="backend-engineering-playbook",
        description="Use when implementing backend API or service tasks that need architecture boundaries, data safety, and verification.",
        title="Backend Engineering Playbook",
        bullets=[
            f"Start at {markdown_link(root / '.cursor/skills/backend-engineering-playbook/SKILL.md', 'ai_docs/START_HERE.md', 'ai_docs/START_HERE.md')}",
            f"Read {markdown_link(root / '.cursor/skills/backend-engineering-playbook/SKILL.md', 'ai_docs/current/backend.md', 'ai_docs/current/backend.md')} for the current backend shape",
            f"Follow {markdown_link(root / '.cursor/skills/backend-engineering-playbook/SKILL.md', 'ai_docs/standards/backend.md', 'ai_docs/standards/backend.md')} for backend rules",
            f"Route implementation via {markdown_link(root / '.cursor/skills/backend-engineering-playbook/SKILL.md', 'ai_docs/workflows/add-backend-feature.md', 'ai_docs/workflows/add-backend-feature.md')}",
            f"Run the backend section in {markdown_link(root / '.cursor/skills/backend-engineering-playbook/SKILL.md', 'ai_docs/reference/verification.md', 'ai_docs/reference/verification.md')}",
        ],
    )
    adapters[
        root / ".cursor" / "skills" / "project-development-playbook" / "SKILL.md"
    ] = build_skill(
        root,
        ".cursor/skills/project-development-playbook/SKILL.md",
        name="project-development-playbook",
        description="Use when implementing project tasks that need consistent coding standards, verification, and frontend stack defaults.",
        title="Project Development Playbook",
        bullets=[
            f"Start at {markdown_link(root / '.cursor/skills/project-development-playbook/SKILL.md', 'ai_docs/START_HERE.md', 'ai_docs/START_HERE.md')}",
            f"Use {markdown_link(root / '.cursor/skills/project-development-playbook/SKILL.md', 'ai_docs/INDEX.md', 'ai_docs/INDEX.md')} to choose backend, frontend, or full-stack flow",
            f"Follow {markdown_link(root / '.cursor/skills/project-development-playbook/SKILL.md', 'ai_docs/workflows/start-task.md', 'ai_docs/workflows/start-task.md')} before implementation",
            f"Use {markdown_link(root / '.cursor/skills/project-development-playbook/SKILL.md', 'ai_docs/standards/engineering.md', 'ai_docs/standards/engineering.md')} for shared rules",
            f"Run the matching section in {markdown_link(root / '.cursor/skills/project-development-playbook/SKILL.md', 'ai_docs/reference/verification.md', 'ai_docs/reference/verification.md')}",
        ],
    )

    skill_specs = {
        ".claude/skills/backend-engineering-playbook/SKILL.md": (
            "backend-engineering-playbook",
            "Use when implementing backend API or service tasks that need architecture boundaries, data safety, and verification.",
            "Backend Engineering Playbook",
            [
                f"Start at {markdown_link(root / '.claude/skills/backend-engineering-playbook/SKILL.md', 'ai_docs/START_HERE.md', 'ai_docs/START_HERE.md')}",
                f"Read {markdown_link(root / '.claude/skills/backend-engineering-playbook/SKILL.md', 'ai_docs/current/backend.md', 'ai_docs/current/backend.md')} for the current backend shape",
                f"Follow {markdown_link(root / '.claude/skills/backend-engineering-playbook/SKILL.md', 'ai_docs/standards/backend.md', 'ai_docs/standards/backend.md')} for backend rules",
                f"Route implementation via {markdown_link(root / '.claude/skills/backend-engineering-playbook/SKILL.md', 'ai_docs/workflows/add-backend-feature.md', 'ai_docs/workflows/add-backend-feature.md')}",
                f"Run the backend section in {markdown_link(root / '.claude/skills/backend-engineering-playbook/SKILL.md', 'ai_docs/reference/verification.md', 'ai_docs/reference/verification.md')}",
            ],
        ),
        ".claude/skills/project-development-playbook/SKILL.md": (
            "project-development-playbook",
            "Use when implementing project tasks that need consistent coding standards, verification, and frontend stack defaults.",
            "Project Development Playbook",
            [
                f"Start at {markdown_link(root / '.claude/skills/project-development-playbook/SKILL.md', 'ai_docs/START_HERE.md', 'ai_docs/START_HERE.md')}",
                f"Use {markdown_link(root / '.claude/skills/project-development-playbook/SKILL.md', 'ai_docs/INDEX.md', 'ai_docs/INDEX.md')} to choose backend, frontend, or full-stack flow",
                f"Follow {markdown_link(root / '.claude/skills/project-development-playbook/SKILL.md', 'ai_docs/workflows/start-task.md', 'ai_docs/workflows/start-task.md')} before implementation",
                f"Use {markdown_link(root / '.claude/skills/project-development-playbook/SKILL.md', 'ai_docs/standards/engineering.md', 'ai_docs/standards/engineering.md')} for shared rules",
                f"Run the matching section in {markdown_link(root / '.claude/skills/project-development-playbook/SKILL.md', 'ai_docs/reference/verification.md', 'ai_docs/reference/verification.md')}",
            ],
        ),
        ".codex/skills/backend-engineering-playbook/SKILL.md": (
            "backend-engineering-playbook",
            "Use when implementing backend API or service tasks that need architecture boundaries, data safety, and verification.",
            "Backend Engineering Playbook",
            [
                f"Start at {markdown_link(root / '.codex/skills/backend-engineering-playbook/SKILL.md', 'ai_docs/START_HERE.md', 'ai_docs/START_HERE.md')}",
                f"Read {markdown_link(root / '.codex/skills/backend-engineering-playbook/SKILL.md', 'ai_docs/current/backend.md', 'ai_docs/current/backend.md')} for the current backend shape",
                f"Follow {markdown_link(root / '.codex/skills/backend-engineering-playbook/SKILL.md', 'ai_docs/standards/backend.md', 'ai_docs/standards/backend.md')} for backend rules",
                f"Route implementation via {markdown_link(root / '.codex/skills/backend-engineering-playbook/SKILL.md', 'ai_docs/workflows/add-backend-feature.md', 'ai_docs/workflows/add-backend-feature.md')}",
                f"Run the backend section in {markdown_link(root / '.codex/skills/backend-engineering-playbook/SKILL.md', 'ai_docs/reference/verification.md', 'ai_docs/reference/verification.md')}",
            ],
        ),
        ".codex/skills/project-development-playbook/SKILL.md": (
            "project-development-playbook",
            "Use when implementing project tasks that need consistent coding standards, verification, and frontend stack defaults.",
            "Project Development Playbook",
            [
                f"Start at {markdown_link(root / '.codex/skills/project-development-playbook/SKILL.md', 'ai_docs/START_HERE.md', 'ai_docs/START_HERE.md')}",
                f"Use {markdown_link(root / '.codex/skills/project-development-playbook/SKILL.md', 'ai_docs/INDEX.md', 'ai_docs/INDEX.md')} to choose backend, frontend, or full-stack flow",
                f"Follow {markdown_link(root / '.codex/skills/project-development-playbook/SKILL.md', 'ai_docs/workflows/start-task.md', 'ai_docs/workflows/start-task.md')} before implementation",
                f"Use {markdown_link(root / '.codex/skills/project-development-playbook/SKILL.md', 'ai_docs/standards/engineering.md', 'ai_docs/standards/engineering.md')} for shared rules",
                f"Run the matching section in {markdown_link(root / '.codex/skills/project-development-playbook/SKILL.md', 'ai_docs/reference/verification.md', 'ai_docs/reference/verification.md')}",
            ],
        ),
    }
    for relative_path, (name, description, title, bullets) in skill_specs.items():
        adapters[root / relative_path] = build_skill(
            root,
            relative_path,
            name=name,
            description=description,
            title=title,
            bullets=bullets,
        )

    return adapters


def sync_adapters(root: Path, *, check: bool) -> list[str]:
    adapters = build_adapter_map(root)
    issues: list[str] = []

    for path, expected in adapters.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == expected:
            continue
        if check:
            issues.append(str(path.relative_to(root)))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")

    return issues


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check whether generated files are up to date without writing changes.",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=get_repo_root(),
        help="Repository root. Defaults to the current project root.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    issues = sync_adapters(args.root.resolve(), check=args.check)
    if not issues:
        print("AI adapters are in sync.")
        return 0

    if args.check:
        print("Out-of-date AI adapters:")
        for issue in issues:
            print(f"- {issue}")
        return 1

    print("Updated AI adapters.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
