#!/usr/bin/env python3
"""Generate thin AI adapter files from canonical ai_docs references."""

from __future__ import annotations

import argparse
import json
import os
import shutil
from pathlib import Path
from textwrap import dedent

CONFIG_FILE = "ai_adapter_config.json"
GENERATED_MARKER = "<!-- Generated by scripts/sync_ai_adapters.py -->"
ROOT_ENTRYPOINTS_SET = "root_entrypoints"
KNOWN_ADAPTER_SETS = frozenset({ROOT_ENTRYPOINTS_SET})
MANAGED_DIRECTORIES = (".agents", ".claude", ".codex", ".cursor")
MANAGED_ROOT_FILES = ("AGENTS.md", "CLAUDE.md")
AdapterConfig = frozenset[str]


def get_repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def rel_link(file_path: Path, target: str) -> str:
    return os.path.relpath(target, start=file_path.parent).replace(os.sep, "/")


def markdown_link(file_path: Path, target: str, label: str) -> str:
    return f"[{label}]({rel_link(file_path, target)})"


def get_default_adapter_config() -> AdapterConfig:
    return frozenset({ROOT_ENTRYPOINTS_SET})


def load_adapter_config(root: Path) -> AdapterConfig:
    path = root / CONFIG_FILE
    if not path.exists():
        return get_default_adapter_config()

    raw = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError(f"{CONFIG_FILE} must contain a JSON object")

    enabled_sets = raw.get("enabled_adapter_sets")
    if enabled_sets is None:
        return get_default_adapter_config()
    if not isinstance(enabled_sets, list) or not all(
        isinstance(item, str) for item in enabled_sets
    ):
        raise ValueError(
            f"{CONFIG_FILE} field 'enabled_adapter_sets' must be a list of strings"
        )

    unknown_sets = sorted(set(enabled_sets) - KNOWN_ADAPTER_SETS)
    if unknown_sets:
        unknown = ", ".join(unknown_sets)
        raise ValueError(f"{CONFIG_FILE} contains unknown adapter set(s): {unknown}")

    return frozenset(enabled_sets)


def build_agents_md(root: Path) -> str:
    path = root / "AGENTS.md"
    start_here = markdown_link(path, "ai_docs/START_HERE.md", "ai_docs/START_HERE.md")
    index = markdown_link(path, "ai_docs/INDEX.md", "ai_docs/INDEX.md")
    verification = markdown_link(
        path, "ai_docs/reference/verification.md", "ai_docs/reference/verification.md"
    )
    return dedent(
        f"""\
        # Project Agent Entrypoint

        {GENERATED_MARKER}

        This file is the cross-tool entrypoint for this repository.

        ## Read order

        1. Start at {start_here}
        2. Use {index} to choose the right task path
        3. Use {verification} before claiming completion

        ## Working rules

        - Treat `ai_docs/` as the only detailed source of truth
        - Read `current/` before `standards/` and `workflows/`
        - Keep changes minimal, typed, and explicit
        - Update docs whenever behavior, structure, scripts, adapters, or public APIs change
        """
    )


def build_claude_md(root: Path) -> str:
    path = root / "CLAUDE.md"
    agents = markdown_link(path, "AGENTS.md", "AGENTS.md")
    tool_entrypoints = markdown_link(
        path,
        "ai_docs/reference/tool-entrypoints.md",
        "ai_docs/reference/tool-entrypoints.md",
    )
    verification = markdown_link(
        path, "ai_docs/reference/verification.md", "ai_docs/reference/verification.md"
    )
    start_task = markdown_link(
        path, "ai_docs/workflows/start-task.md", "ai_docs/workflows/start-task.md"
    )
    return dedent(
        f"""\
        # Claude Code Project Instructions

        {GENERATED_MARKER}

        ## Read order

        1. Start at {agents}
        2. Check tool entrypoints in {tool_entrypoints}
        3. Use {start_task} to route the task
        4. Run the relevant section in {verification}

        ## Claude-specific notes

        - Use {agents} as the shared project entrypoint
        - Route task-specific work through `ai_docs/INDEX.md` and `ai_docs/workflows/`
        - Keep this file thin; detailed rules live in `ai_docs/`
        """
    )


def build_root_entrypoints(root: Path) -> dict[Path, str]:
    return {
        root / "AGENTS.md": build_agents_md(root),
        root / "CLAUDE.md": build_claude_md(root),
    }


def build_adapter_map(
    root: Path, config: AdapterConfig | None = None
) -> dict[Path, str]:
    adapter_config = config or load_adapter_config(root)
    adapters: dict[Path, str] = {}

    if ROOT_ENTRYPOINTS_SET in adapter_config:
        adapters.update(build_root_entrypoints(root))

    return adapters


def list_expected_adapter_files(
    root: Path, config: AdapterConfig | None = None
) -> list[Path]:
    return sorted(build_adapter_map(root, config).keys())


def iter_managed_generated_files(root: Path) -> list[Path]:
    paths: list[Path] = []

    for relative_path in MANAGED_ROOT_FILES:
        path = root / relative_path
        if not path.exists() or not path.is_file():
            continue
        if GENERATED_MARKER in path.read_text(encoding="utf-8"):
            paths.append(path)

    for relative_dir in MANAGED_DIRECTORIES:
        directory = root / relative_dir
        if not directory.exists():
            continue
        for path in sorted(
            candidate for candidate in directory.rglob("*") if candidate.is_file()
        ):
            if GENERATED_MARKER in path.read_text(encoding="utf-8"):
                paths.append(path)

    return paths


def find_stale_generated_files(
    root: Path, config: AdapterConfig | None = None
) -> list[Path]:
    expected = set(list_expected_adapter_files(root, config))
    return [path for path in iter_managed_generated_files(root) if path not in expected]


def prune_stale_generated_files(
    root: Path, config: AdapterConfig | None = None
) -> list[str]:
    removed_files: list[str] = []

    for path in find_stale_generated_files(root, config):
        path.unlink()
        removed_files.append(path.relative_to(root).as_posix())

    for relative_dir in MANAGED_DIRECTORIES:
        directory = root / relative_dir
        if directory.exists() and not any(
            path.is_file() for path in directory.rglob("*")
        ):
            shutil.rmtree(directory)

    return removed_files


def sync_adapters(root: Path, *, check: bool, prune: bool = False) -> list[str]:
    config = load_adapter_config(root)
    adapters = build_adapter_map(root, config)
    issues: list[str] = []

    for path, expected in adapters.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == expected:
            continue
        if check:
            issues.append(str(path.relative_to(root)))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")

    stale_files = find_stale_generated_files(root, config)
    if stale_files:
        if check:
            issues.extend(path.relative_to(root).as_posix() for path in stale_files)
        elif prune:
            prune_stale_generated_files(root, config)

    return issues


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check whether generated files are up to date without writing changes.",
    )
    parser.add_argument(
        "--prune",
        action="store_true",
        help="Remove stale generated files that are no longer enabled by config.",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=get_repo_root(),
        help="Repository root. Defaults to the current project root.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.check and args.prune:
        raise SystemExit("--check and --prune cannot be used together")

    root = args.root.resolve()
    issues = sync_adapters(root, check=args.check, prune=args.prune)
    if not issues:
        print("AI adapters are in sync.")
        return 0

    if args.check:
        print("Out-of-date AI adapters:")
        for issue in issues:
            print(f"- {issue}")
        return 1

    if args.prune:
        print("Updated AI adapters and pruned stale generated files.")
    else:
        print("Updated AI adapters.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
